run:
  deadline: 3m
  skip-dirs:
    - ^pkg/client

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustivestruct
    - exhaustruct
    - goerr113
    - gomnd
    - maligned
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck

issues:
  # Ignore all default error exclusions
  exclude-use-default: false
  # But still keep this exclusions:
  exclude:
    # gosec: Triggered by 'src, err := ioutil.ReadFile(filename)'
    - Potential file inclusion via variable

linters-settings:
  lll:
    # max line length, lines longer will be reported. Default is 120.
    line-length: 120
