version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.21

    steps:
      - checkout

      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2

      - run: golangci-lint run
      - run:
          name: test
          environment:
            TEST_INT: "on"
          command: go test -v ./...
